networks:
  internal:
    name: internal

services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb-ha:pg17
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "5432:5432"
    environment:
      TZ: Europe/Amsterdam
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - timescaledb_data:/var/lib/postgresql/data  # Persistent data storage for TimescaleDB.

  inbucket:
    container_name: inbucket
    image: inbucket/inbucket:latest
    restart: unless-stopped
    networks:
      - internal
    ports:
      - "9000:9000"  # Web UI port.
      - "2500:2500"  # SMTP service port (correct port mapping).
      - "1100:1100"  # POP3 service port.
    volumes:
      - inbucket_data:/data  # Persistent storage for Inbucket's data.

volumes:
  timescaledb_data:  # Volume for TimescaleDB
  inbucket_data:     # Volume for Inbucket
